// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// sstl_fit_to
List sstl_fit_to(const arma::mat& X, const arma::vec& Y, const arma::vec& C, int fam_code, bool aft, double df, int slab_code, bool intercept, double lambda, const List& init, const List& mcmc, Nullable<List> eb, std::string label, int verbose, int width);
RcppExport SEXP _SSTL_sstl_fit_to(SEXP XSEXP, SEXP YSEXP, SEXP CSEXP, SEXP fam_codeSEXP, SEXP aftSEXP, SEXP dfSEXP, SEXP slab_codeSEXP, SEXP interceptSEXP, SEXP lambdaSEXP, SEXP initSEXP, SEXP mcmcSEXP, SEXP ebSEXP, SEXP labelSEXP, SEXP verboseSEXP, SEXP widthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type C(CSEXP);
    Rcpp::traits::input_parameter< int >::type fam_code(fam_codeSEXP);
    Rcpp::traits::input_parameter< bool >::type aft(aftSEXP);
    Rcpp::traits::input_parameter< double >::type df(dfSEXP);
    Rcpp::traits::input_parameter< int >::type slab_code(slab_codeSEXP);
    Rcpp::traits::input_parameter< bool >::type intercept(interceptSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const List& >::type init(initSEXP);
    Rcpp::traits::input_parameter< const List& >::type mcmc(mcmcSEXP);
    Rcpp::traits::input_parameter< Nullable<List> >::type eb(ebSEXP);
    Rcpp::traits::input_parameter< std::string >::type label(labelSEXP);
    Rcpp::traits::input_parameter< int >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< int >::type width(widthSEXP);
    rcpp_result_gen = Rcpp::wrap(sstl_fit_to(X, Y, C, fam_code, aft, df, slab_code, intercept, lambda, init, mcmc, eb, label, verbose, width));
    return rcpp_result_gen;
END_RCPP
}
// sstl_fit_tl
List sstl_fit_tl(const arma::mat& X_T, const arma::vec& Y_T, const arma::vec& C_T, const List& X_s_list, const List& Y_s_list, const List& C_s_list, Nullable<IntegerVector> group_map, int fam_code, bool aft, double df, int slab_code, bool intercept, double lambda_T, const arma::vec& lambda_s, const List& init, const List& mcmc, Nullable<List> eb, std::string label, int verbose, int width);
RcppExport SEXP _SSTL_sstl_fit_tl(SEXP X_TSEXP, SEXP Y_TSEXP, SEXP C_TSEXP, SEXP X_s_listSEXP, SEXP Y_s_listSEXP, SEXP C_s_listSEXP, SEXP group_mapSEXP, SEXP fam_codeSEXP, SEXP aftSEXP, SEXP dfSEXP, SEXP slab_codeSEXP, SEXP interceptSEXP, SEXP lambda_TSEXP, SEXP lambda_sSEXP, SEXP initSEXP, SEXP mcmcSEXP, SEXP ebSEXP, SEXP labelSEXP, SEXP verboseSEXP, SEXP widthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X_T(X_TSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Y_T(Y_TSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type C_T(C_TSEXP);
    Rcpp::traits::input_parameter< const List& >::type X_s_list(X_s_listSEXP);
    Rcpp::traits::input_parameter< const List& >::type Y_s_list(Y_s_listSEXP);
    Rcpp::traits::input_parameter< const List& >::type C_s_list(C_s_listSEXP);
    Rcpp::traits::input_parameter< Nullable<IntegerVector> >::type group_map(group_mapSEXP);
    Rcpp::traits::input_parameter< int >::type fam_code(fam_codeSEXP);
    Rcpp::traits::input_parameter< bool >::type aft(aftSEXP);
    Rcpp::traits::input_parameter< double >::type df(dfSEXP);
    Rcpp::traits::input_parameter< int >::type slab_code(slab_codeSEXP);
    Rcpp::traits::input_parameter< bool >::type intercept(interceptSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_T(lambda_TSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type lambda_s(lambda_sSEXP);
    Rcpp::traits::input_parameter< const List& >::type init(initSEXP);
    Rcpp::traits::input_parameter< const List& >::type mcmc(mcmcSEXP);
    Rcpp::traits::input_parameter< Nullable<List> >::type eb(ebSEXP);
    Rcpp::traits::input_parameter< std::string >::type label(labelSEXP);
    Rcpp::traits::input_parameter< int >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< int >::type width(widthSEXP);
    rcpp_result_gen = Rcpp::wrap(sstl_fit_tl(X_T, Y_T, C_T, X_s_list, Y_s_list, C_s_list, group_map, fam_code, aft, df, slab_code, intercept, lambda_T, lambda_s, init, mcmc, eb, label, verbose, width));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SSTL_sstl_fit_to", (DL_FUNC) &_SSTL_sstl_fit_to, 15},
    {"_SSTL_sstl_fit_tl", (DL_FUNC) &_SSTL_sstl_fit_tl, 20},
    {NULL, NULL, 0}
};

RcppExport void R_init_SSTL(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
