# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

update_target_cpp <- function(bt_c, X_T, Y_T, X_S_list, Y_S_list, bs_c, id, sd_T, lambda_T, lambda_S, tau, tau_S, sd_y_T, sd_y_S, S_max, slab_code) {
    .Call(`_NTL_update_target_cpp`, bt_c, X_T, Y_T, X_S_list, Y_S_list, bs_c, id, sd_T, lambda_T, lambda_S, tau, tau_S, sd_y_T, sd_y_S, S_max, slab_code)
}

update_source_joint_cpp <- function(bs_c, X_s_list, Y_s_list, beta_T, lambda_S, tau_S, sd_y_S, S_max, slab_code) {
    .Call(`_NTL_update_source_joint_cpp`, bs_c, X_s_list, Y_s_list, beta_T, lambda_S, tau_S, sd_y_S, S_max, slab_code)
}

update_target_scale_cpp <- function(xi_t_curr, sd_0, bt_c, bs_c, X_T, Y_T, X_s_list, Y_s_list, lambda_T, lambda_S, sd_y_T, sd_y_S, tau_S, slab_code) {
    .Call(`_NTL_update_target_scale_cpp`, xi_t_curr, sd_0, bt_c, bs_c, X_T, Y_T, X_s_list, Y_s_list, lambda_T, lambda_S, sd_y_T, sd_y_S, tau_S, slab_code)
}

update_source_scales_cpp <- function(xi_s_curr, sd_0, bs_c, X_s_list, Y_s_list, beta_T, lambda_S, sd_y_S, slab_code) {
    .Call(`_NTL_update_source_scales_cpp`, xi_s_curr, sd_0, bs_c, X_s_list, Y_s_list, beta_T, lambda_S, sd_y_S, slab_code)
}

update_target_aft <- function(bt_c, X_T, Y_T, C_T, X_S_list, Y_S_list, C_S_list, bs_c, id, sd_T, lambda_T, lambda_S, tau, tau_S, sd_y_T, sd_y_S, S_max, fam_code, slab_code, approx = FALSE, k_apx = 10.0) {
    .Call(`_NTL_update_target_aft`, bt_c, X_T, Y_T, C_T, X_S_list, Y_S_list, C_S_list, bs_c, id, sd_T, lambda_T, lambda_S, tau, tau_S, sd_y_T, sd_y_S, S_max, fam_code, slab_code, approx, k_apx)
}

update_source_joint_aft <- function(bs_c, X_s_list, Y_s_list, C_s_list, beta_T, lambda_S, tau_S, sd_y_S, S_max, fam_code, slab_code, approx = FALSE, k_apx = 10.0) {
    .Call(`_NTL_update_source_joint_aft`, bs_c, X_s_list, Y_s_list, C_s_list, beta_T, lambda_S, tau_S, sd_y_S, S_max, fam_code, slab_code, approx, k_apx)
}

update_target_scale_aft <- function(xi_t_curr, sd_0, bt_c, bs_c, X_T, Y_T, C_T, X_s_list, Y_s_list, C_s_list, lambda_T, lambda_S, sd_y_T, sd_y_S, tau_S, fam_code, slab_code, approx = FALSE, k_apx = 10.0) {
    .Call(`_NTL_update_target_scale_aft`, xi_t_curr, sd_0, bt_c, bs_c, X_T, Y_T, C_T, X_s_list, Y_s_list, C_s_list, lambda_T, lambda_S, sd_y_T, sd_y_S, tau_S, fam_code, slab_code, approx, k_apx)
}

update_source_scales_aft <- function(xi_s_curr, sd_0, bs_c, X_s_list, Y_s_list, C_s_list, beta_T, lambda_S, sd_y_S, fam_code, slab_code, approx = FALSE, k_apx = 10.0) {
    .Call(`_NTL_update_source_scales_aft`, xi_s_curr, sd_0, bs_c, X_s_list, Y_s_list, C_s_list, beta_T, lambda_S, sd_y_S, fam_code, slab_code, approx, k_apx)
}

update_sigma_target_tl_aft <- function(bt_c, X, Y, C, current_sigma, lambda, tau, fam_code, slab_code, step_size = 0.1, approx = FALSE, k_apx = 10.0) {
    .Call(`_NTL_update_sigma_target_tl_aft`, bt_c, X, Y, C, current_sigma, lambda, tau, fam_code, slab_code, step_size, approx, k_apx)
}

update_sigma_source_tl_aft <- function(bs_col, beta_T, X, Y, C, current_sigma, lambda, tau, fam_code, slab_code, step_size = 0.1, approx = FALSE, k_apx = 10.0) {
    .Call(`_NTL_update_sigma_source_tl_aft`, bs_col, beta_T, X, Y, C, current_sigma, lambda, tau, fam_code, slab_code, step_size, approx, k_apx)
}

update_blocks_cpp <- function(b_c, X, Y, id, sd_0, lambda, tau, sd_y, S_max, slab_code) {
    .Call(`_NTL_update_blocks_cpp`, b_c, X, Y, id, sd_0, lambda, tau, sd_y, S_max, slab_code)
}

update_blocks_aft <- function(b_c, X, Y, C, id, sd_0, lambda, tau, sd_y, S_max, fam_code, slab_code) {
    .Call(`_NTL_update_blocks_aft`, b_c, X, Y, C, id, sd_0, lambda, tau, sd_y, S_max, fam_code, slab_code)
}

update_sigma_to_aft <- function(b_c, X, Y, C, current_sigma, lambda, tau, fam_code, slab_code, step_size = 0.1) {
    .Call(`_NTL_update_sigma_to_aft`, b_c, X, Y, C, current_sigma, lambda, tau, fam_code, slab_code, step_size)
}

update_scale_aft <- function(xi_curr, b_c, X, Y, C, lambda, sd_y, sd_prior = 10.0, fam_code = 1L, slab_code = 1L) {
    .Call(`_NTL_update_scale_aft`, xi_curr, b_c, X, Y, C, lambda, sd_y, sd_prior, fam_code, slab_code)
}

