# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sstl_fit_to <- function(X, Y, C, fam_code, aft, df, slab_code, intercept, lambda, init, mcmc, eb, label, verbose, width) {
    .Call(`_SSTL_sstl_fit_to`, X, Y, C, fam_code, aft, df, slab_code, intercept, lambda, init, mcmc, eb, label, verbose, width)
}

sstl_fit_tl <- function(X_T, Y_T, C_T, X_s_list, Y_s_list, C_s_list, group_map, fam_code, aft, df, slab_code, intercept, lambda_T, lambda_s, init, mcmc, eb, label, verbose, width) {
    .Call(`_SSTL_sstl_fit_tl`, X_T, Y_T, C_T, X_s_list, Y_s_list, C_s_list, group_map, fam_code, aft, df, slab_code, intercept, lambda_T, lambda_s, init, mcmc, eb, label, verbose, width)
}

