# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

update_target_cpp <- function(bt_c, X_T, Y_T, X_S_list, Y_S_list, bs_c, id, sd_T, lambda_T, lambda_S, sd_y_T, sd_y_S, S_max) {
    .Call(`_NTL_update_target_cpp`, bt_c, X_T, Y_T, X_S_list, Y_S_list, bs_c, id, sd_T, lambda_T, lambda_S, sd_y_T, sd_y_S, S_max)
}

update_source_joint_cpp <- function(bs_c, X_s_list, Y_s_list, beta_T, chol_cov_W, lambda_S, sd_y_S, S_max) {
    .Call(`_NTL_update_source_joint_cpp`, bs_c, X_s_list, Y_s_list, beta_T, chol_cov_W, lambda_S, sd_y_S, S_max)
}

